DS-217 env vars passed in file to build-cyverse-rs

diff --git a/build-cyverse-rs b/build-cyverse-rs
--- a/build-cyverse-rs
+++ b/build-cyverse-rs
@@ -8,7 +8,7 @@ show_help()
 build-cyverse-rs
 
 Usage:
- build-cyverse-rs [options] <tag> <script-dir>
+ build-cyverse-rs [options] <tag> <cfg-file> <script-dir>
 
 Builds a docker image containing a resource server configured for the CyVerse
 Data Store. It assumes the Dockerfile is named 'Dockerfile' and is in the
@@ -21,6 +21,7 @@ starts a detached container named 'rs' with the resource server running, and
 
 Parameters:
  <tag>         the docker image tag
+ <env-file>    the file providing the required environment variables, see below
  <script-dir>  the directory where the scripts will be written: defaults to
                current working directory
 
@@ -95,9 +96,18 @@ main()
 
   local tag="$1"
 
-  if [ "$#" -ge 2 ]
+  if [ "$#" -lt 2 ]
   then
-    local scriptDir="$2"
+    printf 'An environment file is required.\n' >&2
+    show_help >&2
+    return 1
+  fi
+
+  local envFile="$2"
+
+  if [ "$#" -ge 3 ]
+  then
+    local scriptDir="$3"
   else
     local scriptDir="$(pwd)"
   fi
@@ -107,6 +117,7 @@ main()
     context=.
   fi
 
+  . "$envFile"
   check_env CYVERSE_DS_CLERVER_PASSWORD
   check_env CYVERSE_DS_CONTROL_PLANE_KEY
   check_env CYVERSE_DS_NEGOTIATION_KEY
